nodejs:
  image: makeomatic/website:nodejs
  container_name: nodejs
  restart: always
  expose:
    - "8080"

nginx:
  image: makeomatic/website:nginx
  restart: always
  container_name: nginx
  links:
    - "nodejs"
  ports:
    - "443:443"
    - "80:80"