version: '2'

volumes:
  certs-volume:
  vhost-volume:
  confd-volume:
  html-volume:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - certs-volume:/etc/nginx/certs:ro
      - vhost-volume:/etc/nginx/vhost.d
      - confd-volume:/etc/nginx/conf.d
      - html-volume:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "443:443"
      - "80:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx
    depends_on:
      - nginx-gen
    volumes:
      - certs-volume:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  website:
    image: makeomatic/website:latest
    restart: always
    container_name: website
    environment:
      - HOST=0.0.0.0
      - VIRTUAL_HOST=makeomatic.ru,www.makeomatic.ru,en.makeomatic.ru,makeomatic.co,makeomatik.ru,make-o-matic.ru,make-o-matik.ru
      - LETSENCRYPT_HOST=makeomatic.ru,www.makeomatic.ru,en.makeomatic.ru,makeomatic.co,makeomatik.ru,make-o-matic.ru,make-o-matik.ru
      - LETSENCRYPT_EMAIL=v@makeomatic.ru
    depends_on:
      - nginx-letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


