menu:
  Home: /
  Archives: /archives

widgets:
- category
- tag

excerpt_link: Читать дальше...

twitter: makeomatic
google_plus: "https://plus.google.com/+MakeomaticRu"

addthis:
  enable: true

fancybox: false

google_analytics:
rss: